### ISSUE TITLE
nuxt.vueApp.runWithContext is not a function

### ISSUE THREAD

**Issue by razbakov** [loicpennequin/create-v3-app#18]
I run `yarn dev` and getting this error:

```bash
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] nuxt.vueApp.runWithContext is not a function
  at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.js:165:24)  
  at ./node_modules/nuxt/dist/app/nuxt.js:35:54  
  at EffectScope.run (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:41:24)  
  at Object.runWithContext (./node_modules/nuxt/dist/app/nuxt.js:35:44)  
  at applyPlugin (./node_modules/nuxt/dist/app/nuxt.js:115:39)  
  at Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.js:131:21)  
  at createNuxtAppServer (./node_modules/nuxt/dist/app/entry.js:23:35)  
  at __vite_ssr_exports__.default (./node_modules/nuxt/dist/app/entry.js:76:41)  
  at default (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:33:24)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

node: 18.12.0

**Comment by razbakov** [comment]
Issue https://github.com/nuxt/nuxt/issues/20901 is solved by updating vue with `yarn add vue`
